export const interests = [
  '#vegan',
  '#vegetarian',
  '#gamer',
  '#geek',
  '#yoga',
  '#books',
  '#travel',
  '#musiclover',
  '#cinemabuff',
  '#art',
  '#tattoos',
  '#piercings',
  '#coffee',
  '#tea',
  '#catperson',
  '#doglover',
  '#sustainability',
  '#fitness',
  '#introvert',
  '#extrovert',
  '#dancing',
  '#hiking',
  '#camping',
  '#boardgames',
  '#lgbtqfriendly',
  '#fashion',
  '#photography',
  '#foodie',
  '#languagelearner',
  '#openrelationships',
];

export const genderList = [
  'man',
  'woman',
  'non-binar',
  'transgender',
  'other',
  'prefer not to say',
];